Weatherfy/base/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import PasswordChange, EditProfile
app_name = "base"
urlpatterns = [
    path("", views.home, name="home"),
    path("admin", admin.site.urls),
    path("callback", views.callback, name="callback"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("home", views.home, name="home"),
    path("profile", views.profile, name="profile"),
    path("playlists", views.playlists, name="playlists"),
    path("location", views.location, name="location"),
    path("friends", views.friends, name="friends"),
    path("about", views.about, name="about"),
    path("userLogin", views.userLogin, name="userLogin"),
    path("userLogout", views.userLogout, name="userLogout"),
    path("register", views.register, name="register"),
    path("editprofile", EditProfile.as_view(), name="editprofile"),
    path("password/", PasswordChange.as_view(template_name='base/changepass.html')),
    path('togglePlayPause/', views.togglePlayPause, name='togglePlayPause'),
    path('skipForward/', views.skipForward, name='skipForward'),
    path('playSong/', views.playSong, name='playSong'),
    path('skipBackward/', views.skipBackward, name='skipBackward'),
    path('toggleFavorite/', views.toggleFavorite, name='toggleFavorite'),
]

Weatherfy/base/templates/base/changepass.html
{% extends 'base/main.html' %}

{% block content %}
<div class="d-flex justify-content-center mt-3 login_container">
	<h1>Change Password</h1>
	</br></br>
	<div class="form">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-secondary">Update Password</button>
	</div>
</div>
{% endblock content %}

Weatherfy/base/templates/base/createprofile.html
{% if user.is_authenticated %}
	<h1>Create Profile Page...</h1>
	<br/><br/>

	<div class="form-group">
<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}

			{{ form.as_p }}
			<button class="btn btn-secondary">Create Profile Page</button>
	</div>

	

{% else %}

Unauthorized User

{% endif %}

Weatherfy/base/templates/base/editprofile.html
{% extends 'base/main.html' %}

{% block content %}
{% if user.is_authenticated %}
		<div class="d-flex justify-content-center mt-3 login_container">
			<h1>Edit Profile</h1>
			</br></br>
			<div class="d-flex justify-content-center">

				<div class="form-group">
					<form method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						
						{{ form.as_p }}
						<button class="btn btn-secondary">Update Profile</button>
				</div>
			</div>
		</div>
{% else %}
You must <a href="/login">Login</a>
{% endif %}


{% endblock content %}

Weatherfy/base/templates/base/home.html
{% extends 'base/main.html' %}

{% block content %}

<title>Weatherfy | Home</title>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
    <p>You must <a href="/login">connect your Spotify account</a> </p>

    {% if error != None %}
    <p>Error: {{ error }}</p>
    {% endif %}

  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Your Daily Playlist</b></h1>
    <h1 class="w3-xxxlarge w3-text-red"><b>Current Weather: {{ weather.temperature }}</b></h1>
    <h3>Location: {{ weather.city }}, {{ weather.country_code }} ({{ weather.description|title }})</h3>
    <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="">
    <hr style="width:50px;border:5px solid red" class="w3-round">

    <center class="row">
      <form action="/home" method="POST">
        {% csrf_token %}
        <div class="input-group">
          <input type="text" required class="form-control" name="city"
            placeholder="Listen to weather from a different city">
          <div class="input-group-append">
            <button class="btn btn-success" type="submit">
              Search
            </button>
          </div>
        </div>
      </form>
    </center>
  </div>

  <hr />

  <div>
    <h1>Curated Spotify Playlist</h1>

    <div>
      <h4>Title</h4>
      <p>{{ playlist.name }}</p>

      <h4>Description</h4>
      <p>{{ playlist.description }}</p>

      <h4>Tracks</h4>
      <p>{{ playlist.tracks.total }}</p>


      {% for p in playlist.images %}
      {% if forloop.counter == 1 %}
      <img src="{{ p.url }}" height="240" width="240" />
      {% endif %}
      {% endfor %}
    </div>

    <p><a href="/logout">Logout</a> </p>
  </div>

</div>


{% endblock content %}

Weatherfy/base/templates/base/location.html
{% extends 'base/main.html' %}

{% block content %}
<title>Weatherfy | Location</title>

<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
	<div class="w3-container" style="margin-top:80px" id="showcase">
	<h1 class="w3-jumbo"><b>Your Location</b></h1>
	<h1 class="w3-xxxlarge w3-text-red"><b>Current Weather: Rain</b></h1>
	<hr style="width:50px;border:5px solid red" class="w3-round">
    
	</div>


	<div class="container">
		<div class="row mt-4">
			<div class="col-md-10 offset-md-1">
				{{m|safe}}
			</div>
		</div>
	</div>
</div>
</br></br>
{% endblock content %}

Weatherfy/base/templates/base/login.html
{% extends 'base/main.html' %}

{% block content %}
<title>Weatherfy | Login</title>

<div class="d-flex justify-content-center mt-3 login_container">
	<body>
		<div class="container h-100">
			<div class="d-flex justify-content-center h-100">
				<div class="user_card">
					<div class="d-flex justify-content-center">


						<h3 id="form-title">LOGIN</h3>
					</div>
					<div class="d-flex justify-content-center form_container">
						<form method="POST" action="">
							{% csrf_token %}
							<div class="input-group mb-3">
								<input type="text" name="username" placeholder="Username..." class="form-control">
							</div>
							<div class="input-group mb-2">
									<input type="password" name="password" placeholder="Password..." class="form-control" >
							</div>

								<div class="d-flex justify-content-center mt-3 login_container">
					 				<input class="btn login_btn" type="submit" value="Login">
					   			</div>
						</form>

					</div>
					<div class="d-flex justify-content-center mt-3 login_container">

					{% for message in messages %}
						<p id="messages">{{message}}</p>
					{% endfor %}			
					</div>
					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							Don't have an account?<a href="{% url 'base:register' %}" class="ml-2">Sign Up</a>
						</div>
				
					</div>
				</div>
			</div>
		</div>
	</body>
</div>

{% endblock content %}

Weatherfy/base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
	<style>
		body,
		h1,
		h2,
		h3,
		h4,
		h5 {
			font-family: "Montserrat", sans-serif
		}

		body {
			font-size: 16px;
		}

		.w3-half img {
			position: relative;
			justify-content: center;
			margin-bottom: 0px;
			margin-top: 0px;
			opacity: 0.8;
			cursor: pointer
			padding: 10px;
		}
		
		.w3-half {
			position: relative;
			justify-content: center;
			margin-bottom: 0px;
			margin-top: 0px;
		}

		.w3-half img:hover {
			opacity: 1
		}
		
		.form_container {
			margin-top: 20px;
		}
		
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
		}
		
		.center {
  			display: block;
  			margin-left: auto;
  			margin-right: auto;
  			width: 100%;
		}
		
		
		.card {
			margin-top: 500px;
 			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  			max-width: 300px;
  			margin: auto;
  			text-align: center;
  			font-family: "Montserrat", sans-serif
		}
		.title {
  			color: grey;
  			font-size: 18px;
		}
	</style>
	<!-- Latest compiled and minified CSS -->
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
	{% include 'base/navbar.html' %}
	{% block content %}
	<!-- Content here -->
	{% endblock content %}

</html>

Weatherfy/base/templates/base/navbar.html
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-green w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>Weatherfy</b></h3>
  </div>
  <div class="w3-bar-block">
    <a href="/home" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a> 
    <a href="/profile" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Profile</a> 
    <a href="/playlists" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Playlists</a> 
    <a href="/location" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Location</a> 
    <a href="/friends" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Friends</a> 
    <a href="/about" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">About</a>
    {% if user.is_authenticated %}
    <a href="/userLogout" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Logout</a>
    {% else %}
    <a href="/userLogin" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Login</a>
    {% endif %}
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-green w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-green w3-margin-right" onclick="w3_open()">☰</a>
  <span>Weatherfy</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>


<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

Weatherfy/base/templates/base/playlists.html
{% extends 'base/main.html' %}
{% block content %}
<title>Weatherfy | Playlists</title>
<h1>Playlists</h1>

{% if user == None %}
<p>You must <a href="/login">login</a> </p>
{% else %}

<script>
	var auth = document.cookie.substring(13, document.cookie.indexOf(";"));
	var is_playing = false;

	function onPlaylistSelect(playlist_id)
	{
		var xmlHttp = new XMLHttpRequest();
		xmlHttp.open( "GET", "https://api.spotify.com/v1/playlists/"+playlist_id+"/tracks", false ); // false for synchronous request
		xmlHttp.setRequestHeader("Authorization", "Bearer " + auth)
		xmlHttp.send( null );
		var tracks = JSON.parse(xmlHttp.responseText).items;
		var table = document.getElementById("shown_playlist");
		table.innerHTML = "";
		for (var i = 0; i < tracks.length; ++i)
		{
			table.innerHTML += '<tr><th scope="row">'+(i+1)+'</th><th style="text-align: center;"><form action="playSong" method="GET"><input type="hidden" name="trackID" value="'
								+tracks[i].track.id+'" /><input type="hidden" name="playlistID" value="'+playlist_id+'" /><button class="track-button" type="submit" type="submit">'+tracks[i].track.name+'</button></form></th></tr>';
		}
	}

	window.setInterval(function()
	{
		var xmlHttp = new XMLHttpRequest();
		xmlHttp.open( "GET", "https://api.spotify.com/v1/me/player", false ); // false for synchronous request
		xmlHttp.setRequestHeader("Authorization", "Bearer " + auth)
		xmlHttp.send( null );
		if(is_playing != JSON.parse(xmlHttp.responseText).is_playing)
		{
			var player_play_pause_button = document.getElementById("player_pause_stop");
			is_playing = !is_playing;
			if(is_playing)
			{
				player_play_pause_button.innerHTML = '<i class="fa fa-pause fa-2x"></i>';
			}
			else
			{
				player_play_pause_button.innerHTML = '<i class="fa fa-play fa-2x"></i>';
			}
		}
	}, 200);
</script>

<style>
	.track-button
	{
		background-color: rgb(118, 239, 255);
		border-radius: 10px;
		border-width: 1px;
	}
	.track-button:hover
	{
		background-color: #2BAE66FF;
	}
</style>

<div class="jumbotron jumbotron-fluid" style="left:15%;right:0;position: absolute;">
	<div class="container">
		<h3 class="display-4" style="text-align: center;font-family: Arial, Helvetica, sans-serif;font-weight: 800;font-size: xxx-large;margin-bottom: 20px;color: rgb(211, 0, 0);">My Playlist</h3>

		<table style="margin: auto;width:50%;table-layout: fixed;width: 370px;background-color: #2BAE66FF;border-radius: 20px;height: 50px;margin-bottom: 20px;margin-top: 20px;">
			<tr class="track-player" >
				<td style="text-align: center;" class="previoustrack">
					<form action='skipBackward' method='GET'>
						<button type="submit" style="border-radius: 30px;">
							<i class="fa fa-arrow-left fa-2x"></i>
						</button>
					</form>
				</td>
				<td style="text-align: center;">
					<form action='togglePlayPause' method='GET'>
						<button type="submit" style="border-radius: 30px;width: 100px;" id="player_pause_stop">
							<i class="fa fa-play fa-2x"></i>
						</button>
					</form>
				</td>
				<td style="text-align: center;">
					<form action='skipForward' method='GET'>
						<button type="submit" style="border-radius: 30px;">
							<i class="fa fa-arrow-right fa-2x"></i>
						</button>
					</form>
				</td>
				<td style="text-align: center;width: 50px;padding-right: 70px;">
					<form action='toggleFavorite/' method='POST'>
						{% csrf_token %}
						<button type="submit" style="border-radius: 30px;">
							<i class="fa fa-star fa-2x"></i>
						</button>
					</form>
				</td>
			</tr>
		</table>
		<select class="selectpicker dropdown-menu-center" data-style="btn-danger" onchange="onPlaylistSelect(this.value)" style="font-size: large;margin: auto;width:40%;text-align: center;display: block;border-radius: 20px;">
			<option value={{current_playlist_id}}>{{ current_playlist_name }}</option>
			{% for id, name in playlists %}
				<option value={{id}}>{{ name }}</option>
			{% endfor %}
		</select>

		<hr/>

		<table class="table table-striped" style="width: 70%;margin: auto;margin-top: 20px;">
			<thead>
				<tr>
					<th scope="col" style="font-size: x-large;color: rgb(211, 0, 0);">#</th>
					<th scope="col" style="text-align: center;font-size: x-large;color: rgb(211, 0, 0);">Track(s)</th>
				</tr>
			</thead>
			<tbody id="shown_playlist">
				{% for trackID, name in tracks %}
				<tr>
					<th scope="row">{{ forloop.counter }}</th>
					<th style="text-align: center;">
						<form action='playSong' method='GET'>
							<input type="hidden" name="trackID" value="{{trackID}}" />
							<input type="hidden" name="playlistID" value="{{current_playlist_id}}" />
							<button class="track-button" type="submit" type="submit">{{ name }}</button>
						</form>
					</th>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<p>You must <a href="/logout">logout</a> </p>
</div>

{% endif %}
{% endblock content %}

Weatherfy/base/templates/base/profile.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<title>Weatherfy | Profile</title>
<div class="d-flex justify-content-center mt-3">
	<div class="card">
		{% if user.profile.spotifyLink %}
			<img src="{{ user.profile.profile_image.url }}" class="center" width=200 height=200>
		{% else %}
			<img src="{% static 'base/images/default-user.png' %}" class="center" width=200 height=200>
			{% endif %}
		<h2>{{username|safe}}</h2>
		<p class="title">{{address|safe}}</p>
		{% if user.profile.spotifyLink %}
			<a href = "{{ user.profile.spotifyLink }}">Spotify</a>
		{% else %}
		Spotify Not Connected
		{% endif %}
		<div class="d-flex justify-content-center">
			<a href="{% url 'base:editprofile' %}" class="button">Edit Profile</a>
		</div>
	</div>
	</br></br>
	
</div>


{% endblock content %}

Weatherfy/base/templates/base/register.html
{% extends 'base/main.html' %}
{% block content %}


<title>Weatherfy | Register</title>
<div class="d-flex justify-content-center mt-3 login_container">
	<body>
		<div class="w3-container">
			<div class="d-flex justify-content-center h-100">
				<div class="user_card">
					<div class="d-flex justify-content-center">
						<h3 id="form-title">REGISTER ACCOUNT</h3>
					</div>
					<div class="d-flex justify-content-center form_container">

						<form method="POST" action="">
							{% csrf_token %}
							<div class="input-group mb-3">
								
								{{form.username}}
							</div>
							<div class="input-group mb-2">
								
								{{form.email}}
							</div>
							<div class="input-group mb-2">
								
								{{form.password1}}
							</div>
							<div class="input-group mb-2">
								
								{{form.password2}}
							</div>

					   		<div class="d-flex justify-content-center mt-3 login_container">
					 			<input class="btn login_btn" type="submit" value="Register Account">
					   		</div>
						</form>
					</div>
			
					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							Already have an account? <a href="{% url 'base:userLogin' %}" class="ml-2">Login</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script>
							/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
			//We start indexing at one because CSRF_token is considered and input field 
			 */

			//Query All input fields
			var form_fields = document.getElementsByTagName('input')
			form_fields[1].placeholder='Username..';
			form_fields[2].placeholder='Email..';
			form_fields[3].placeholder='Enter password...';
			form_fields[4].placeholder='Re-enter Password...';


			for (var field in form_fields){	
				form_fields[field].className += ' form-control'
			}
		</script>
	</body>
</div>

{% endblock content %}